# 🐍Python Spracovanie a Vizualizácia Dát

🐼 Pandas - nástroj na manipuláciu s tabuľkovými údajmi v Pythone. Je to obrovská knižnica, ale ak poznáte správne metódy, môžeme vytvoriť výkonnú analýzu.

🚀 Numpy - knižnica jazyka Python, ktorá poskytuje infraštruktúru pre prácu s vektormi, maticami a všeobecne viacrozmernými poliami.

BeautifulSoup  

https://www.python.org/about/apps/

In [30]:
try:
    from matplotlib import pyplot as plt
    import numpy as np
    import pandas as pd
    import math
    
    data_zamestnanci = {
        "Zamestnanci" : ["Monika", "Martin", "Peter", "Pavol", "Ivana"],
        "Vek" : [24, 29, 37, 52, 21]
    }
    
#     Vytvor objekt typu dataframe/tabulka z premennej/objektu data_zamestnanci
    print("\ndf_zamestnanci:")
    df_zamestnanci = pd.DataFrame(data_zamestnanci)
    print(df_zamestnanci)
    
    hmotnosti = [2, 5, 7, 9, 11]
#     df_hmotnosti = pd.DataFrame(hmotnosti)
    print("\ndf_hmotnosti:")
    df_hmotnosti = pd.Series(hmotnosti)
    print(df_hmotnosti)
    print("Maximalny pocet riadkov -->", pd.options.display.max_rows)
#     pd.options.display.max_rows = 1000000
    print("Maximalny pocet riadkov -->", pd.options.display.max_rows)
    
    print("\nPrva hmotnost -->", df_hmotnosti[0])
    print("Velkost tabulky -->", df_hmotnosti.size)
    print("Posledna hmotnosti -->", df_hmotnosti[df_hmotnosti.size - 1])
    print("Prva hmotnost -->", df_hmotnosti.loc[0])  
    print("Riadok 0 a 1 [[0, 1]]: ")
    print(df_hmotnosti.loc[[0, 1]])
    
    print("\ndf_hmotnosti2 vlastne indexy:")
    df_hmotnosti2 = pd.Series(hmotnosti, index = ["a", "a", "c", "d", "e"])
    print(df_hmotnosti2)
    print("a -->", df_hmotnosti2.loc["a"])
    print("a -->", df_hmotnosti2[0])
    
    print("\ncountries.csv")
    df_krajiny = pd.read_csv("Datasety\countries.csv")
    print(df_krajiny)
    
except:
    print("Moduly neboli nacitane...")
    
finally:
    pass


df_zamestnanci:
  Zamestnanci  Vek
0      Monika   24
1      Martin   29
2       Peter   37
3       Pavol   52
4       Ivana   21

df_hmotnosti:
0     2
1     5
2     7
3     9
4    11
dtype: int64
Maximalny pocet riadkov --> 1000000
Maximalny pocet riadkov --> 1000000

Prva hmotnost --> 2
Velkost tabulky --> 5
Posledna hmotnosti --> 11
Prva hmotnost --> 2
Riadok 0 a 1 [[0, 1]]: 
0    2
1    5
dtype: int64

df_hmotnosti2 vlastne indexy:
a     2
a     5
c     7
d     9
e    11
dtype: int64
a --> a    2
a    5
dtype: int64
a --> 2

countries.csv
                       country  year  population
0                  Afghanistan  1952     8425333
1                  Afghanistan  1957     9240934
2                  Afghanistan  1962    10267083
3                  Afghanistan  1967    11537966
4                  Afghanistan  1972    13079460
5                  Afghanistan  1977    14880372
6                  Afghanistan  1982    12881816
7                  Afghanistan  1987    13867957
8       

## II. Nacitanie dat z externého zdroja

In [62]:
try:
    from matplotlib import pyplot as plt
    import numpy as np
    import pandas as pd
    import math
    
    print("\ncountries.csv")
    df_krajiny = pd.read_csv("Datasety\countries.csv")
#     print(df_krajiny)
#     print(df_krajiny.to_string())
    # Prvych 5 zaznamov/riadkov
#     print(df_krajiny.head())
    
#     # Prvych 10 zaznamov/riadkov
#     print(df_krajiny.head(10))
    
#     # Poslednych 5 zaznamov/riadkov
#     print(df_krajiny.tail())
    
#     # Poslednych 10 zaznamov/riadkov
#     print(df_krajiny.tail(10))
    
#     # Informacie o dataframe
#     print(df_krajiny.info())

     # Operacie s tabulkou
    print("\nVelkosti/pocty hodnot -->") 
    print(df_krajiny.count())
    
#     print("\nAritmeticky priemer -->")
#     print(df_krajiny.mean())
    
#     print("\nMedian -->")
#     print(df_krajiny.median())
    
    print("\nMax-->")
    print(df_krajiny.max())
    
    print("\nMin-->")
    print(df_krajiny.min())
    
#     print("\nModus-->")
#     print(df_krajiny.mode())
    
    print("\nCorr-->")
    print(df_krajiny.corr())
    
    print("\nCorr-->")
    print(df_krajiny.describe())
    
    df_krajiny.plot()
    df_krajiny.plot(kind = "scatter", x = "year", y = "population")
    
    # Zmazanie duplicit
    df_krajiny.drop_duplicate(inplace = True)
    
    # Zmazanie null
    df_krajiny.dropna(inplace = True)
    
    # Nahradenie null hodnoty 120
    df_krajiny.fillna(120 ,inplace = True)
    
except:
    print("Moduly neboli nacitane...")
    
finally:
    pass
    


countries.csv

Velkosti/pocty hodnot -->
country       1704
year          1704
population    1704
dtype: int64

Max-->
country         Zimbabwe
year                2007
population    1318683096
dtype: object

Min-->
country       Afghanistan
year                 1952
population          60011
dtype: object

Corr-->
                year  population
year        1.000000    0.082308
population  0.082308    1.000000

Corr-->
             year    population
count  1704.00000  1.704000e+03
mean   1979.50000  2.960121e+07
std      17.26533  1.061579e+08
min    1952.00000  6.001100e+04
25%    1965.75000  2.793664e+06
50%    1979.50000  7.023596e+06
75%    1993.25000  1.958522e+07
max    2007.00000  1.318683e+09
Krajiny: 
                       country  year  population
10                 Afghanistan  2002    25268405
11                 Afghanistan  2007    31889923
22                     Albania  2002     3508512
23                     Albania  2007     3600523
34                     Algeria 

## III. Nacitanie dat z Excelu

In [71]:

    from matplotlib import pyplot as plt
    import numpy as np
    import pandas as pd
    import math
    
    print("\ndata-excel.xlsx")
    df_excel = pd.read_excel("Datasety\data-excel.xlsx")
    print(df_excel.info())
    
    print("\nPred odstranenim duplicit")
    print(df_excel)
    
    
    print("\nPo odstranenim duplicit")
    df_excel2 = df_excel.drop_duplicates(inplace = True)
    print(df_excel2)
    



data-excel.xlsx
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Mena     4 non-null      object
 1   Produkt  4 non-null      object
 2   Cena     5 non-null      int64 
dtypes: int64(1), object(2)
memory usage: 248.0+ bytes
None

Pred odstranenim duplicit
     Mena    Produkt  Cena
0  Martin   Notebook   100
1   Maria   Notebook   200
2     Eva        NaN   300
3     NaN  Projektor   400
4     Oto  Projektor   500

Po odstranenim duplicit


ValueError: Need to specify at least one of 'labels', 'index' or 'columns'

In [ ]:
from __future__ import print_function, division
import pandas as pd

bp_data = pd.read_csv("path/to/file.csv", header=1, delim_whitespace=True)
bp_data.to_csv("path/to/new_file.csv", sep="", header=False, index=False)
bp_data = bp_data.dropna()
bp_data = bp_data.fillna(0.0)
bp_num_values = bp_data[["Numerical column 1", "Numerical column 2"]].values


## IV. Numpy tvorba polí

In [79]:
import numpy as np

zoznam = [1,2,3,4,5]
pole = np.array(zoznam)

print(pole)
print(type(pole))

skalar = np.array(42)
vektor = np.array([10, 20, 30])
vektor3D = np.array([[10, 20, 30], [10, 20, 30], [10, 20, 30], [10, 20, 30]])

print(skalar.ndim)
print(vektor.ndim)
print(vektor3D.ndim)

teserakt = np.array([10, 20, 30], ndmin = 4)
print(teserakt)
print(teserakt.ndim)


[1 2 3 4 5]
<class 'numpy.ndarray'>
0
1
2
[[[[10 20 30]]]]
4


## V. Numpy slicing

In [122]:
from __future__ import print_function, division
import numpy as np

print("\nnulove matice")
new_array = np.zeros((4,3,), dtype=float)
print(new_array)

print("\njednotkove matice")
new_array = np.ones((4,3,), dtype=float)
print(new_array)

print("\nVyberat data z pola/slicing")
pole_cisel = np.array([0,1,2,3,4,5,6,7,8,9])
print("0. index/1. polozka -->", pole_cisel[0])
print("1. index/2. polozka -->", pole_cisel[1])

print("Posledna polozka -->", pole_cisel[-1])
print("Predposledna polozka -->", pole_cisel[-2])

print(pole_cisel[1:5])
print(pole_cisel[1:])
print(pole_cisel[5:])

print(pole_cisel[:5])

print(pole_cisel[0:5:2])
print(pole_cisel[1:5:2])


print(pole_cisel[::2])
print(pole_cisel[1::2])

print(pole_cisel[-5:-2:-1])
print(pole_cisel[-2:-5:-1])

print(pole_cisel.dtype)
print(pole_cisel.dtype.name)




nulove matice
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

jednotkove matice
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Vyberat data z pola/slicing
0. index/1. polozka --> 0
1. index/2. polozka --> 1
Posledna polozka --> 9
Predposledna polozka --> 8
[1 2 3 4]
[1 2 3 4 5 6 7 8 9]
[5 6 7 8 9]
[0 1 2 3 4]
[0 2 4]
[1 3]
[0 2 4 6 8]
[1 3 5 7 9]
[]
[8 7 6]
int32
int32


In [139]:
from __future__ import print_function, division
import numpy as np

pole = np.array([1, 2], dtype="i4")
print(pole.dtype)
print(pole.dtype.name)

np.concatenate()



int32
int32


In [140]:
!pip list

Package                            Version
---------------------------------- --------------------
alabaster                          0.7.12
anaconda-client                    1.9.0
anaconda-navigator                 2.1.1
anaconda-project                   0.10.1
anyio                              2.2.0
appdirs                            1.4.4
argh                               0.26.2
argon2-cffi                        20.1.0
arrow                              0.13.1
asgiref                            3.5.0
asn1crypto                         1.4.0
astroid                            2.6.6
astropy                            4.3.1
async-generator                    1.10
atomicwrites                       1.4.0
attrs                              21.2.0
autopep8                           1.5.7
Babel                              2.9.1
backcall                           0.2.0
backports.functools-lru-cache      1.6.4
backports.shutil-get-terminal-size 1.0.0
backports.tempfile                 

## VI.BeautifulSoup (Scrapping/Parsing web)

In [146]:
from bs4 import BeautifulSoup
import requests

headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'}

def zisti_pocasie(mesto):
    mesto = mesto.replace(" ", "+")
    res = requests.get(
    f'https://www.google.com/search?q={mesto}&oq=      {mesto}&aqs=chrome.0.35i39l2j0l4j46j69i60.6128j1j7&sourceid=chrome&ie=UTF-8', headers=headers)

    print("Hladam...\n")

    soup = BeautifulSoup(res.text, 'html.parser')
    poloha = soup.select('#wob_loc')[0].getText().strip()
    cas = soup.select('#wob_dts')[0].getText().strip()
    info = soup.select('#wob_dc')[0].getText().strip()
    pocasie = soup.select('#wob_tm')[0].getText().strip()
    vlhkost = soup.select('#wob_hm')[0].getText().strip()

    print("Poloha -->", poloha)
    print("Den a cas -->", cas)
    print("Pocasie -->", info)
    print("Teplota -->", pocasie, "°C")
    print("Vlhkost -->", vlhkost)

mesto = input("Zadajte názov ľubovoľného mesta: ")
mesto = mesto + " pocasie"
zisti_pocasie(mesto)

Zadajte názov ľubovoľného mesta: Alicante
Hladam...

Poloha --> Alicante, Španielsko
Den a cas --> štvrtok 13:00
Pocasie --> Jasno
Teplota --> 26 °C
Vlhkost --> 59%


In [157]:
try:
    from matplotlib import pyplot as plt
    import numpy as np
    import pandas as pd
    import math
    print("Moduly boli nacitane")
    
    raise TypeError("Mas zly typ")
    
except TypeError:
    print("Mas zly typ")
      
except ModuleNotFoundError:
    print("Moduly neboli nacitane...")
    
except:
    print("Nastala nejaka chyba...")
    
finally:
    pass

Kod je OK
Nastala nejaka chyba...


In [161]:

    from matplotlib import pyplot as plt
    import numpy as np
    import pandas as pd
    import math
    
    print("\ndata-excel.xlsx")
    df_excel = pd.read_excel("Datasety\data-excel.xlsx")
    
    print("\nPred odstranenim null")
    print(df_excel)
    
    print("\nPo odstranenim null 1")
    df_excel2 = df_excel["Mena"].dropna(inplace = True)
    print(df_excel2)
    
    print("\nPo odstranenim null 2")
    df_excel2 = df_excel.dropna(inplace = True)
    print(df_excel2)
    
if a.size > 0:  # Never use `if a` or `if len(a)` for numpy arrays
    print(a)
    
    



data-excel.xlsx

Pred odstranenim null
     Mena    Produkt  Cena
0  Martin   Notebook   100
1   Maria   Notebook   200
2     Eva        NaN   300
3     NaN  Projektor   400
4     Oto  Projektor   500

Po odstranenim null 1
None

Po odstranenim null 2
None


In [ ]:
# This is an example snippet!
# To create your own, add a new snippet block to the
# snippets.json file in your jupyter nbextensions directory:
# /nbextensions/snippets/snippets.json
import this

In [163]:
!pip install forex-python
